sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: KMP
name: Kaung Myat Paing
description: Junior Web Developer

github: https://github.com/Kaung-myat-paing/ 
email: mailto:kmyat5258@gmail.com
facebook: https://facebook.com/kmyat.me
rss: false

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
